### ISSUE TITLE
Netlify api url.

### ISSUE THREAD

**Issue by notiv-nt** [snipcart/gratitude-journal#1]
There is hard-coded url:

https://github.com/snipcart/gratitude-journal/blob/469a1400ea20e5bf2b16038bfaab043f61baae0c/static/app.js#L5

What is it? Where can I get this?

**Comment by couellet** [comment]
You'll find all the steps we made to create this demo here on our blog: https://snipcart.com/blog/headless-cms-graphql-takeshape-tutorial

**Comment by notiv-nt** [comment]
no no no, i did it 3 times, and every time, i got:

2 sites:

![image](https://user-images.githubusercontent.com/10743009/52524313-b12ca180-2cac-11e9-837f-a10a88deba9a.png)

Because:

> Fill the form by selecting Netlify as provider. You’ll be able to generate a new Netlify site directly from this form.

Ok, 1:1 as at the picture

And:

1 function on https://hardcore-snyder-f909b9.netlify.com/  -> but 'page not found'

![image](https://user-images.githubusercontent.com/10743009/52524328-d7ead800-2cac-11e9-8ba0-c84e597b4e3f.png)

and 0 functions at https://takeshape-gratitude-journal-site.netlify.com/

![image](https://user-images.githubusercontent.com/10743009/52524341-efc25c00-2cac-11e9-84b8-a64e833f7f14.png)

whatever I entered in the field it is not sent to takeshape

**Comment by notiv-nt** [comment]
if i will choose first as primary

![image](https://user-images.githubusercontent.com/10743009/52524381-62cbd280-2cad-11e9-8924-2ea7cdf88d14.png)

I got a site https://hardcore-snyder-f909b9.netlify.com/

but still 0 functions 

![image](https://user-images.githubusercontent.com/10743009/52524391-75dea280-2cad-11e9-8c44-b0e4b9d53873.png)

**Comment by couellet** [comment]
The way you did it first is the good one. It's normal that it returns a Not Found, this Netlify site is just hosting your function. You shouldn't use this URL to access your _public_ website.

You must create a second site that you will deploy with Takeshape. In your site code, you will need to change `https://takeshape-gratitude-journal-api.netlify.com` to `https://hardcore-snyder-f909b9.netlify.com`

This second site is the one that you will visit in your browser, and the code in `app.js` will make a request to your API that should be hosted on hardcore-snyder-f909b9.netlify.com.

I'll try to explain this somehow in the post next week.

**Comment by notiv-nt** [comment]
ok, super, I figured it out, thank you
